syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";
import "enums/chase_patrol_skill_type.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message ChasePatrolSkill {
  .enums.ChasePatrolSkillType skill_type = 1;
  string name_lang_id = 2;
  string description_lang_id = 3;
  int32 effect_duration_millisecond = 100;
  int32 relief_effect_duration_extension_millisecond = 101;
  int32 cool_time_millisecond = 102;
  int32 relief_cool_time_reduction_millisecond = 103;
  int32 start_cool_time_progress_rate_permil_multiply = 104;
  float radar_arrow_display_range = 200;
  float radar_arrow_switch_range = 201;
  float radar_icon_display_range = 202;
  int32 speed_up_coefficient_permil_multiply = 300;
  float stealth_transparent_rate = 400;
  float stealth_transparent_rate_from_others = 401;
}
