syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";
import "enums/combo_card_game_play_type.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message ComboCardGame {
  string id = 1;
  .enums.ComboCardGamePlayType play_type = 2;
  int64 start_time = 3;
  int64 end_time = 4;
  string combo_card_game_card_group_id = 5;
  string game_start_display_clear_condition_lang_id = 6;
  string game_playing_display_clear_condition_lang_id = 7;
}
