syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message CookingPuzzleRecipe {
  string id = 1;
  string name_lang_id = 2;
  string description_lang_id = 3;
  string character_id = 4;
  string cooking_puzzle_foodstuff_id1 = 5;
  int32 required_quantity1 = 6;
  string cooking_puzzle_foodstuff_id2 = 7;
  int32 required_quantity2 = 8;
  string cooking_puzzle_foodstuff_id3 = 9;
  int32 required_quantity3 = 10;
  string image_asset_id = 11;
}
