syntax = "proto3";

package entity.master;

import "common/reward.gen.proto";
import "entity/master/options/master.proto";
import "enums/cooking_puzzle_play_type.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message CookingPuzzle {
  string id = 1;
  .enums.CookingPuzzlePlayType play_type = 2;
  string view_condition_group_id = 3;
  string unlock_condition_group_id = 4;
  int32 limit_time_seconds = 5;
  int64 shuffle_cool_time_milliseconds = 6;
  string cooking_puzzle_combo_group_id = 7;
  int32 loop_start_stage_number = 8;
  string cooking_puzzle_completion_count_reward_group_id = 10;
  string game_start_display_clear_condition_lang_id = 11;
  string mode_select_display_clear_condition_lang_id = 12;
  int32 order = 999;
  repeated .common.SimplifiedReward play_rewards = 1000;
}
