syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";
import "enums/costume_rarity_type.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message Costume {
  string id = 1;
  string character_id = 2;
  string name_lang_id = 3;
  string live_leader_skill_id = 4;
  string asset_id = 5;
  string expression_asset_id = 6;
  string live_start_character_voice_id = 7;
  .enums.CostumeRarityType rarity_type = 8;
  int32 order = 999;
}
