syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";
import "enums/jump_rope_gimmick_type.gen.proto";
import "enums/jump_rope_invisible_gimmick_type.gen.proto";
import "enums/jump_rope_phase_type.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message JumpRopePhaseGimmick {
  string group_id = 1;
  enums.JumpRopePhaseType phase_type = 2;
  int32 jump_count_from = 3;
  repeated enums.JumpRopeGimmickType gimmick_types = 4;
  int32 speed_coefficient_permil_multiply = 5;
  int32 speed_up_coefficient_permil_multiply = 6;
  int32 speed_down_coefficient_permil_multiply = 7;
  int32 caution_wait_jump_count_min = 8;
  int32 caution_wait_jump_count_max = 9;
  int32 caution_active_jump_count_min = 10;
  int32 caution_active_jump_count_max = 11;
  int32 gimmick_active_jump_count_min = 12;
  int32 gimmick_active_jump_count_max = 13;
  enums.JumpRopeInvisibleGimmickType invisible_gimmick_type = 14;
  float min_steam_density = 15;
  float max_steam_density = 16;
  float min_fall_object_size = 17;
  float max_fall_object_size = 18;
}
