syntax = "proto3";

import "entity/master/options/master.proto";

package entity.master;

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message LiveSpecialCardDialogue {
	option (options.master.table) = true;

	string card_id = 1 [(options.master.fk) = "Card:id", (options.master.pk) = true];
	string leader_character_id = 2 [(options.master.fk) = "Character:id", (options.master.pk) = true];
	string live_dialogue_voice_id = 3 [(options.master.fk) = "LiveDialogueVoice:id"];
}
