syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";
import "enums/live_skin_type.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message LiveSkin {
  string id = 1;
  .enums.LiveSkinType skin_type = 2;
  string name_lang_id = 3;
  string description_lang_id = 4;
  string character_production_id = 5;
  string asset_id1 = 6;
  string asset_id2 = 7;
  string thumbnail_asset_id = 8;
  string icon_asset_id = 9;
  bool is_default = 10;
  string default_character_effect_live_skin_id = 11;
  string color1 = 100;
  string color2 = 101;
  string color3 = 102;
  int32 order = 999;
}
