syntax = "proto3";

import "entity/master/options/master.proto";

package entity.master;

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message ParkRandomSymbol {
	option (options.master.table) = true;

	string area_id = 1 [(options.master.fk) = "Area:id", (options.master.pk) = true];
	string park_target_mapping_id = 2 [(options.master.fk) = "ParkTargetMapping:id", (options.master.pk) = true];
	string condition_group_id = 3 [(options.master.fk) = "Condition:group_id", (options.master.optional) = true];
}
