syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";
import "enums/resource_background_pattern_type.gen.proto";
import "enums/resource_type.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message ResourceTypeDetail {
  .enums.ResourceType type = 1;
  string color = 2;
  string name_lang_id = 3;
  string icon_asset_id = 4;
  string description_lang_id = 5;
  string resource_obtainment_route_group_id = 6;
  string background_color = 7;
  .enums.ResourceBackgroundPatternType background_pattern_type = 8;
}
