syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";
import "enums/card_attribute_type.gen.proto";
import "enums/skill_tree_effect_target_type.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message SkillTreeEffectTarget {
  string id = 1;
  enums.SkillTreeEffectTargetType type = 2;
  int32 target_count = 3;
  string character_id = 4;
  string character_grouping_id = 5;
  enums.CardAttributeType card_attribute_type = 6;
  string description_lang_id = 1000;
}
