syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";
import "enums/cheat_parameter_type.gen.proto";
import "enums/cheat_severity_type.gen.proto";
import "enums/cheat_type.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message Cheat {
  enums.CheatType type = 1;
  enums.CheatSeverityType severity_type = 2;
  enums.CheatParameterType parameter_type = 3;
  int64 threshold = 4;
}
