syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message LiveActiveSkillLevel {
  string live_active_skill_id = 1;
  int32 level = 2;
  string live_skill_trigger_group_id = 3;
  string live_active_skill_effect_group_id = 4;
  string additional_live_skill_trigger_group_id = 5;
  string additional_live_active_skill_effect_group_id = 6;
  int32 cool_time_millisecond = 7;
  int32 activation_probability_permil_multiply = 8;
  int32 limit_count = 9;
  int32 effect_duration_millisecond = 10;
  string description_lang_id = 1000;
}
