syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";
import "enums/loading_display_type.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message LoadingDisplay {
  string id = 1;
  .enums.LoadingDisplayType type = 2;
  string title_lang_id = 3;
  string text_lang_id = 4;
  string asset_id = 6;
  string character_id = 7;
  int32 ratio = 8;
  string condition_group_id = 9;
}
