syntax = "proto3";

package entity.master;

import "entity/master/options/master.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/master";
option csharp_namespace = "Vision.Common.Proto.Master";

message Membership {
  string shop_charge_item_subscription_shop_charge_item_id = 1;
  repeated string character_ids = 2;
  string name_lang_id = 3;
  repeated string stamp_ids = 4;
  repeated string emblem_ids = 5;
  repeated string fan_mark_ids = 6;
  string character_coin_item_id = 7;
  int32 character_coin_item_quantity = 8;
  int32 first_join_reward_character_coin_item_quantity = 9;
  string character_coin_exchange_booth_group_id = 10;
  string thumbnail_asset_id = 11;
  string motion_asset_id = 12;
  int64 notification_start_time = 13;
}
