syntax = "proto3";

package rpc.api;

import "common/reward.gen.proto";
import "entity/master/options/master.proto";
import "enums/card_attribute_type.gen.proto";
import "enums/card_rarity.gen.proto";
import "enums/event_type.gen.proto";
import "enums/mini_game_type.gen.proto";
import "enums/tips_hint_type.gen.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "options/check_option.proto";
import "options/zap.proto";
import "rpc/api/common/response.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/rpc/api";
option csharp_namespace = "Vision.Common.Proto.Api";

message EventListEventInfoResponse {
  message EventInfo {
    message MarathonInfo {
      message MarathonChapter {
        message MarathonScoreReward {
          int64 score = 1;
          repeated .common.Reward rewards = 2;
        }
        message MarathonScoreRankingRankReward {
          string group_id = 1;
          int64 end_rank = 2;
          repeated .common.Reward rewards = 3;
          string marathon_ranking_grade_id = 4;
        }
        message MarathonMusicHighestScoreRankingRankReward {
          string group_id = 1;
          string music_id = 2;
          int64 end_rank = 3;
          repeated .common.Reward rewards = 4;
          string marathon_ranking_grade_id = 5;
        }
        message MarathonTotalMusicHighestScoreRankingReward {
          string group_id = 1;
          int64 end_rank = 2;
          repeated .common.Reward rewards = 3;
          string marathon_ranking_grade_id = 4;
        }
        message MarathonMusicScoreBonus {
          string group_id = 1;
          string music_id = 2;
          int32 number = 3;
          string character_id = 4;
          string card_id = 5;
          .enums.CardAttributeType card_attribute_type = 6;
          .enums.CardRarity card_rarity = 7;
          int64 card_potential_upgrade_count = 8;
          int32 score_up_permil_up = 9;
        }
        message MarathonMiniGameMarathonScoreBonus {
          string group_id = 1;
          int32 number = 2;
          string card_id = 3;
          .enums.CardRarity card_rarity = 4;
          int64 card_potential_upgrade_count = 5;
          int32 marathon_score_quantity_up_permil_up = 6;
        }
        message MarathonLiveMarathonScoreBonus {
          string group_id = 1;
          int32 number = 2;
          string character_id = 3;
          string card_id = 4;
          .enums.CardAttributeType card_attribute_type = 5;
          .enums.CardRarity card_rarity = 6;
          int64 card_potential_upgrade_count = 7;
          int32 marathon_score_quantity_up_permil_up = 8;
        }
        message MarathonMiniGameMarathonScoreRate {
          string group_id = 1;
          .enums.MiniGameType mini_game_type = 2;
          int32 marathon_score_permil_multiply = 3;
          int32 bonus_permil_up = 4;
        }
        string id = 1;
        int32 chapter_number = 2;
        string character_id = 3;
        int64 end_time = 4;
        string score_name = 5;
        string score_icon_asset_id = 6;
        string marathon_event_badge_item_id = 7;
        string mission_group_id = 8;
        repeated EventListEventInfoResponse.EventInfo.MarathonInfo.MarathonChapter.MarathonScoreReward marathon_score_rewards = 9;
        int64 score = 10;
        string event_story_chapter_id = 11;
        string auto_play_story_id = 12;
        string background_asset_id = 13;
        string bgm_asset_id = 14;
        int64 ranking_reveal_start_time = 15;
        repeated EventListEventInfoResponse.EventInfo.MarathonInfo.MarathonChapter.MarathonScoreRankingRankReward marathon_score_ranking_rank_rewards = 16;
        repeated EventListEventInfoResponse.EventInfo.MarathonInfo.MarathonChapter.MarathonMusicHighestScoreRankingRankReward marathon_music_highest_score_ranking_rank_rewards = 17;
        repeated EventListEventInfoResponse.EventInfo.MarathonInfo.MarathonChapter.MarathonTotalMusicHighestScoreRankingReward marathon_total_music_highest_score_ranking_rewards = 18;
        repeated EventListEventInfoResponse.EventInfo.MarathonInfo.MarathonChapter.MarathonMusicScoreBonus marathon_music_score_bonuses = 19;
        repeated EventListEventInfoResponse.EventInfo.MarathonInfo.MarathonChapter.MarathonMiniGameMarathonScoreBonus marathon_mini_game_marathon_score_bonuses = 20;
        repeated EventListEventInfoResponse.EventInfo.MarathonInfo.MarathonChapter.MarathonLiveMarathonScoreBonus marathon_live_marathon_score_bonuses = 21;
        repeated EventListEventInfoResponse.EventInfo.MarathonInfo.MarathonChapter.MarathonMiniGameMarathonScoreRate marathon_mini_game_marathon_score_rates = 22;
      }
      string exchange_booth_group_id = 1;
      int64 aggregation_start_time = 2;
      int64 aggregated_ranking_reveal_start_time = 3;
      repeated EventListEventInfoResponse.EventInfo.MarathonInfo.MarathonChapter marathon_chapters = 4;
      bool is_marathon_score_ranking_disable = 5;
      .enums.TipsHintType tips_hint_type = 6;
    }
    string event_id = 1;
    .enums.EventType type = 2;
    string name = 3;
    int64 start_time = 4;
    int64 end_time = 5;
    int64 exchange_end_time = 6;
    string logo_asset_id = 7;
    string background_asset_id = 8;
    bool is_new = 9;
    bool is_noti = 10;
    string mission_group_id = 11;
    string view_condition_group_id = 12;
    string unlock_condition_group_id = 13;
    EventListEventInfoResponse.EventInfo.MarathonInfo marathon_info = 14;
  }
  repeated EventListEventInfoResponse.EventInfo event_infos = 1;
  common.Response common_response = 9999;
}

message EventListEventInfoForPortalResponse {
  message EventInfo {
    string event_id = 1;
    .enums.EventType type = 2;
    string name = 3;
    int64 start_time = 4;
    int64 end_time = 5;
    int64 exchange_end_time = 6;
    string logo_asset_id = 7;
    string background_asset_id = 8;
    bool is_new = 9;
    bool is_noti = 10;
    string mission_group_id = 11;
    string view_condition_group_id = 12;
    string unlock_condition_group_id = 13;
  }
  repeated EventListEventInfoForPortalResponse.EventInfo event_infos = 1;
  common.Response common_response = 9999;
}

service Event {
  rpc ListEventInfo (.google.protobuf.Empty) returns (EventListEventInfoResponse);
  rpc ListEventInfoForPortal (.google.protobuf.Empty) returns (EventListEventInfoForPortalResponse);
}
