syntax = "proto3";

package rpc.api;

import "buf/validate/validate.proto";
import "enums/friend_status_type.gen.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "options/check_option.proto";
import "options/zap.proto";
import "rpc/api/common/profile.gen.proto";
import "rpc/api/common/response.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/rpc/api";
option csharp_namespace = "Vision.Common.Proto.Api";

message FriendTopResponse {
  message LatestPlayedUserInfo {
    common.BasicUserInfo user_info = 1;
    .enums.FriendStatusType friend_status_type = 2;
  }
  repeated common.BasicUserInfo friend_user_infos = 1;
  repeated common.BasicUserInfo offer_user_infos = 2;
  repeated common.BasicUserInfo offer_received_user_infos = 3;
  repeated FriendTopResponse.LatestPlayedUserInfo latest_played_user_infos = 4;
  common.Response common_response = 9999;
}

message FriendTopReloadResponse {
  repeated common.BasicUserInfo friend_user_infos = 1;
  repeated common.BasicUserInfo offer_user_infos = 2;
  repeated common.BasicUserInfo offer_received_user_infos = 3;
  common.Response common_response = 9999;
}

message FriendSearchUserRequest {
  string public_user_id = 1;
}

message FriendSearchUserResponse {
  common.BasicUserInfo user_info = 1;
  common.Response common_response = 9999;
}

message FriendDeleteFriendRequest {
  string public_user_id = 1;
}

message FriendOfferRequest {
  string public_user_id = 1;
}

message FriendApproveOfferRequest {
  string public_user_id = 1;
}

message FriendCancelOfferRequest {
  string public_user_id = 1;
}

message FriendRejectOfferRequest {
  string public_user_id = 1;
}

message FriendDeleteFriendResponse {
  common.Response common_response = 9999;
}

message FriendOfferResponse {
  common.Response common_response = 9999;
}

message FriendApproveOfferResponse {
  common.Response common_response = 9999;
}

message FriendCancelOfferResponse {
  common.Response common_response = 9999;
}

message FriendRejectOfferResponse {
  common.Response common_response = 9999;
}

service Friend {
  rpc Top (.google.protobuf.Empty) returns (FriendTopResponse);
  rpc TopReload (.google.protobuf.Empty) returns (FriendTopReloadResponse);
  rpc SearchUser (FriendSearchUserRequest) returns (FriendSearchUserResponse);
  rpc DeleteFriend (FriendDeleteFriendRequest) returns (FriendDeleteFriendResponse);
  rpc Offer (FriendOfferRequest) returns (FriendOfferResponse);
  rpc ApproveOffer (FriendApproveOfferRequest) returns (FriendApproveOfferResponse);
  rpc CancelOffer (FriendCancelOfferRequest) returns (FriendCancelOfferResponse);
  rpc RejectOffer (FriendRejectOfferRequest) returns (FriendRejectOfferResponse);
}
