syntax = "proto3";

package rpc.api;

import "buf/validate/validate.proto";
import "entity/master/options/master.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "options/check_option.proto";
import "rpc/api/common/response.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/rpc/api";
option csharp_namespace = "Vision.Common.Proto.Api";

message CardGetParameterRequest {
  string card_id = 1;
}

message CardGetParameterResponse {
  message SkillTreeEffect {
    int32 performance_up = 1;
    float performance_up_permil_up = 2;
    int32 technique_up = 3;
    float technique_up_permil_up = 4;
    int32 sense_up = 5;
    float sense_up_permil_up = 6;
  }
  int64 parameter = 1;
  int64 performance = 2;
  int64 technique = 3;
  int64 sense = 4;
  CardGetParameterResponse.SkillTreeEffect skill_tree_effect = 5;
  common.Response common_response = 9999;
}

message CardGetParametersResponse {
  message ParameterInfo {
    string card_id = 1;
    int64 parameter = 2;
    int64 performance = 3;
    int64 technique = 4;
    int64 sense = 5;
  }
  repeated CardGetParametersResponse.ParameterInfo parameter_infos = 1;
  int32 live_deck_power_permyriad_up_by_card_level_up = 2;
  common.Response common_response = 9999;
}

message CardLevelUpRequest {
  string card_id = 1;
  int32 after_level = 2;
}

message CardLevelLimitBreakRequest {
  string card_id = 1;
  int32 after_level_limit_break_count = 2;
}

message CardUpgradePotentialRequest {
  string card_id = 1;
  int32 after_potential_upgrade_count = 2;
}

message CardLevelUpResponse {
  common.Response common_response = 9999;
}

message CardLevelLimitBreakResponse {
  common.Response common_response = 9999;
}

message CardUpgradePotentialResponse {
  common.Response common_response = 9999;
}

service Card {
  rpc GetParameter (CardGetParameterRequest) returns (CardGetParameterResponse);
  rpc GetParameters (google.protobuf.Empty) returns (CardGetParametersResponse);
  rpc LevelUp (CardLevelUpRequest) returns (CardLevelUpResponse);
  rpc LevelLimitBreak (CardLevelLimitBreakRequest) returns (CardLevelLimitBreakResponse);
  rpc UpgradePotential (CardUpgradePotentialRequest) returns (CardUpgradePotentialResponse);
}
