syntax = "proto3";

package rpc.api;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "options/check_option.proto";
import "options/zap.proto";
import "rpc/api/common/response.gen.proto";
import "rpc/api/common/user_data.gen.proto";

option go_package = "github.com/qua-vision/vision-server/pkg/pb/rpc/api";
option csharp_namespace = "Vision.Common.Proto.Api";

message UserGetResponse {
  common.UserData user_data = 1;
}

message UserDeleteResponse {
  common.Response common_response = 9999;
}

service User {
  rpc Get (.google.protobuf.Empty) returns (UserGetResponse);
  rpc Delete (.google.protobuf.Empty) returns (UserDeleteResponse);
}
